name: ${name}
main: com.volmit.react.React
version: ${version}
authors: [ NextdoorPsycho, Cyberpwn ]
api-version: ${apiversion}
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.8.9
commands:
  react:
    aliases: [ re ]
    permission: op