name: ${name}
main: com.volmit.react.React
version: ${version}
authors: [ NextdoorPsycho, Cyberpwn ]
api-version: ${apiversion}
commands:
  react:
    aliases: [ re ]
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - io.timeandspace:smoothie-map:2.0.2
  - com.github.ben-manes.caffeine:caffeine:3.0.5
  - it.unimi.dsi:fastutil:8.5.8
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.10
  - org.zeroturnaround:zt-zip:1.15
  - org.bitbucket.mstrobel:procyon-core:0.6.0
  - org.bitbucket.mstrobel:procyon-compilertools:0.6.0
  - org.bitbucket.mstrobel:procyon-reflection:0.6.0
  - fr.inria.gforge.spoon:spoon-core:10.2.0
  - org.eclipse.jetty:jetty-server:11.0.15
  - org.eclipse.jetty.websocket:websocket-server:9.4.51.v20230217
  - org.eclipse.jetty.websocket:websocket-api:9.4.51.v20230217
  - javax.websocket:javax.websocket-api:1.1
